service: go-uniswap-etherscan-aws-serverless

provider:
  name: aws
  profile: ${file(env.json):AWS_PROFILE}
  runtime: go1.x
  environment:
    ETHERSCAN_API_KEY: ${file(env.json):ETHERSCAN_API_KEY}

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  main:
    handler: bin/main
    events:
      - http:
          path: /{walletAddress}
          method: get
          cors: true
          request:
            parameters:
              paths:
                walletAddress: true
